### PR TITLE
WIP German Language Support

### PR DESCRIPTION
**Pull request by V1ncNet**
Adds german language JSON file and a new option in language selection.

I hope its still ok for you when I create a PR against `re-write` an not against `dev`.

### CODE REVIEW

**Comment by kiswa** [comment]
Re-write is definitely where this should go (at least until I push it to dev.

Thank you for the contribution! I'll be waiting a bit before merging, but I really do appreciate this.

**Comment by V1ncNet** [comment]
That's nice to hear :+1:. I'll inform you when I remove the WIP state

**Comment by kiswa** [comment]
@V1ncNet Are the translations to German still happening?

**Comment by V1ncNet** [comment]
Totally forgot about this PR. I'll resume my work this weekend or next week.

**Comment by kiswa** [comment]
No worries, glad to hear it will still happen!

**Comment by kiswa** [comment]
Would you mind moving this PR to the `dev` branch now that `re-write` has been merged?

**Pull request closed without merging**
