### PR TITLE
Add check for mod_expires in the api .hraccess

### PR DESCRIPTION
**Pull request by mbasaglia**
This check was already in the top-level .htaccess but not in the one under api/

### CODE REVIEW

**Comment by mbasaglia** [comment]
That Codacy thing does not look properly configured

**Comment by MarlonSchultz** [comment]
Are you re-commiting this pull ? I just ran into the same problem and had to fix the .htaccess as well.

**Comment by kiswa** [comment]
@mbasaglia Codacy is setup to work with the `re-write` branch. You can safely ignore it here for now.

**Comment by mbasaglia** [comment]
I changed the base branch for the request, but can't re-open it.

**Pull request merged**
