### PR TITLE
Updated compatibility of arrays with PHP 5.x.

### PR DESCRIPTION
**Pull request by praveenscience**
**Updated compatibility of arrays with PHP 5.x.**

* Added `array()` instead of just `[]`.
* Created a new variable for `function_call()[]` type of array calling.
* The both forms are not supported in PHP 5.x.

---

I am using WAMPServer with PHP 5.x, which doesn't recognize the below forms:

* `[]`
* `function_call()[]`

So I have updated the code to be compatible with **PHP 5.5-**.

Please accept my pull request. I have verified the correctness and it works well. Thanks. Please let me know if you have any questions. Also, guys, you are awesome! Love your product. :+1: :smile: 

**Update:** Sorry, by mistake I created a PR to the master branch. Please forgive for the same.

Cheers,
Praveen Kumar

### CODE REVIEW

**Comment by kiswa** [comment]
I am still considering this pull request. The current code supports PHP 5.4 or newer. Your changes allow for versions prior to 5.4, however I need to verify the remaining codebase for other possible incompatibilities.

**Comment by praveenscience** [comment]
@kiswa Since I am using the PHP 5.2.x, I am trialling out your application and it seems to work fine. I will keep you updated or create new PRs, if something doesn't work on my system. What do you think? Would you like to merge this?

**Comment by kiswa** [comment]
That seems reasonable.

**Comment by praveenscience** [comment]
I will support you. Don't worry. Just assign me... :)

**Comment by praveenscience** [comment]
I have deleted the branch too.. :D

**Pull request merged**
